import { Geist, Geist_Mono, Roboto_Slab} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer} from 'react-toastify';
import Footer from "@/components/Footer";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Wanderlast Project",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en" 
      className={`${robotoSlab.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}

